import type { Metadata } from "next";

import "./globals.css";
import localFont from 'next/font/local'

const  myFont = localFont({
  src: [
    {
      path: '/fonts/Gilroy-Medium.ttf',
      weight: '400'
    },
    {
      path: '/fonts/Gilroy-Bold.ttf',
      weight: '700'
    }
  ],
  variable: '--font-poppins'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
